run-compose:
	sudo docker compose up -d

build-compose:
	sudo docker compose up -d --build

down-compose:
	sudo docker compose down

run-app:
	go run cmd/main.go

build-app:
	go build -o out/main cmd/main.go

tidy:
	go mod tidy
